### ISSUE TITLE
Audo service does not run on Openelec 5.0.6

### ISSUE THREAD

**Issue by ee0u4179** [lsellens/script.service.audo#11]
Was fine until 5.0.6 upgrade. Now the service does not start.

Tried starting manually by SSHing in (python service.py). Not sure if this is the right thing to do but I thought I would give it a shot. I get the following error:

  File "service.py", line 1, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj

**Comment by hypnot0ad** [comment]
I also have this issue, assuming there is a fix as its closed?

**Comment by ee0u4179** [comment]
Lsellens has rolled out a fix for this. Upgrade to version 1.8.

**Comment by JaggedJax** [comment]
I just started getting this error with audo service 1.1.9 and openelec 4.2.1.

Trying to figure out what to do but there's not much about this error except here and a few posts on the openelec forum where lsellens was looking into it for the kodi betas.

**Comment by lsellens** [comment]
I'm about to push a big update real soon. I'll check back if you’re still having this issue after the update.

**Comment by lsellens** [comment]
1.2.0 is up on the repo. Let me know if you still have issues after updating.

**Comment by JaggedJax** [comment]
I updated to 1.2.0. I also realized I was on an old Openelec so I updated that to 5.0.8 and uninstalled and reinstalled audo.

Whenever Audo is enabled, this is the message in the kodi.log file:

    ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                   Error Type: <type 'exceptions.ImportError'>
                   Error Contents: No module named configobj
                   Traceback (most recent call last):
                     File "/storage/.kodi/addons/script.service.audo/service.py", line 1, in <module>
                       from configobj import ConfigObj
                   ImportError: No module named configobj
                   -->End of Python script error report<--
    DEBUG: ------ Window Init (DialogKaiToast.xml) ------
     INFO: Python script stopped

**Comment by JaggedJax** [comment]
I wrote than and then immediately realized that after re-installing, that audo-dependencies and audo-programs were marked as disabled. I re-enabled them and all is well!

It must have noticed them marked as disabled after the issue with the older openelec and disabled them automatically.
