### ISSUE TITLE
Can't install/start the service after current update

### ISSUE THREAD

**Issue by andre217** [lsellens/script.service.audo#12]
After installing the update on my openelec system, the audo applications won't start. Getting further into the issue, it seems as if I can't install the service-component of audo.

Any ideas on this?

**Comment by lsellens** [comment]
Sounds like you're not waiting long enough for all the files to get extracted. When downloading it will appear to be stuck sometimes for a very long time. Don't reboot or stop it just wait it will finish eventually.

**Comment by andre217** [comment]
I tried removing and reinstalling - but with no success. Do I need a fresh install to get this fixed?

**Comment by lsellens** [comment]
Can you give me some details of what is happening?

**Comment by andre217** [comment]
Alright, it was user fault. Sorry for stressing about it - it was just my hard drive running out of space. After cleaning up stuff, everything went fine.
Thank you very much!
