### ISSUE TITLE
Question: does SickRAGE work on android?

### ISSUE THREAD

**Issue by dmarcelino** [lsellens/script.service.audo#14]
With the release of [NVIDIA Shield Android TV](http://forum.kodi.tv/showthread.php?tid=220297) I've been wondering, does `audo`, namely SickRAGE, work on android? Has anyone tried?

Thanks!

PS: thanks @lsellens for your work on `audo`!

**Comment by lsellens** [comment]
Can you run tour own OS on it? kodi or openelec? Just glancing at its hardware specs it looks like it should. Its a 64 bit arch, so I don’t see why not. If you have one please test it and let me know.

**Comment by dmarcelino** [comment]
Unfortunately I don't have one. I'm trying to decide between buying an Intel Braswell machine or the Shield Android TV. Thanks anyway!

**Comment by pleguit** [comment]
Hi Lsellens, 

My SABNZB stopped working (no change from myside) on my NUC 24/7 After multiple reboots, and SSH into my Box I noticed the SAB and SICK would run due to cheetah issues. This happens.. I decided to reimage my NUC and start from scratch no backup using. 

I'll give my 2 cents, got a clean install of openelec 5.0.8 Kodi 14.2 GIT:7CC53A9

just imported the library as per your tagline. AUDO is a option, and so is sickrage to install. I installed Audo first, and received the message: Install AUDO Service, which made sense as I saw it before. However AUDO doesnt start, the AUDO.SERVICE is not an option. Sixckrage works, however I prefer Newz so torrents are not a option. 

your help is appreciated. 

Pat

**Comment by pleguit** [comment]
Reading my own post, I have to add that your great system was working for over a year! Kudo's

**Comment by lsellens** [comment]
Kodi has different add-on categories. Install the one under the service section. Installing just the one under programs will not work on its own.

**Comment by dmarcelino** [comment]
@lsellens, these last couple of days I've been playing with wrapping SickRAGE in an APK using [Kivy / Buildozer](http://kivy.org/docs/guide/packaging-android.html) but got stuck while trying to compile with the following error:

```
assets/private.mp3: /home/kivy/sickrage/.buildozer/android/app/cache/sessions/0/e/6/8/3/0e68370f33c3966e5e3138a6e6f0cff1a3a2f34b3c7cb9b35bff9584
assets/private.mp3: /home/kivy/sickrage/.buildozer/android/app/cache/sessions/6/5/0/f/5/650f5dfd66f5302b4e3487f7e734ecfdd5dce20304807f43d8a1124c
assets/private.mp3: /home/kivy/sickrage/.buildozer/android/app/cache/cheetah/_home_kivy_sickrage_gui_slick_interfaces_default_home_tmpl.pyo
Traceback (most recent call last):
  File "build.py", line 508, in <module>
    make_package(args)
  File "build.py", line 344, in make_package
    'res/drawable-xhdpi/ouya_icon.png')
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: '/home/kivy/sickrage/'
# Command failed: /usr/bin/python build.py --name SickRAGE --version 0.0.1 --package tv.sickrage --private /home/kivy/sickrage/.buildozer/android/app --sdk 14 --minsdk 8 --permission INTERNET --ouya-category GAME --ouya-icon /home/kivy/sickrage/ --orientation landscape --window debug
#
# Buildozer failed to execute the last command
```

Seems related to Cheetah, which I tried installing / uninstalling but never really mattered. Anyway I'll report any further progress (if it happens).

**Comment by dmarcelino** [comment]
For anyone interested in this I've raised SiCKRAGETV/sickrage-issues#2437 to gather some support from the SiCKRAGE community. So far the reaction has been positive.
