### ISSUE TITLE
SickRage web ui wont load anymore.  

### ISSUE THREAD

**Issue by jarrodprice** [lsellens/script.service.audo#15]
I have a feeling an automatic update broke it.  I am not sure how to restore it.  All the other audo plugins are working fine

**Comment by tuurie** [comment]
I have the same.  Seems indeed related to an update.  However I am using openelec so I am not able to use git to do a manual update.  Is there anyway to only reinstall sickbeard without also removing couchpotato?  https://github.com/SiCKRAGETV/sickrage-issues/issues/2158

**Comment by jarrodprice** [comment]
I managed to get it back on by re-installing audo, but I guess I had auto update on because in a day it crashed again.

**Comment by lsellens** [comment]
I haven’t gotten around to releasing any updates for a long while now. Shouldn't be related to an update.

**Comment by tuurie** [comment]
Well I also did a manual update in sickrage 
Op 3 aug. 2015 6:27 AM schreef lsellens <notifications@github.com>:I haven’t gotten around to releasing any updates for a long while now. Shouldn't be related to an update.

**Comment by tuurie** [comment]
But anyway,  is there any way to reinstall sickrage without completely removing audo? 

Op 3 aug. 2015 07:34 schreef Arthur Duineveld <tuurie@hotmail.com>:Well I also did a manual update in sickrage 
Op 3 aug. 2015 6:27 AM schreef lsellens <notifications@github.com>:I haven’t gotten around to releasing any updates for a long while now. Shouldn't be related to an update.

**Comment by jarrodprice** [comment]
I am wondering if there is a way to add the Git function to Openelec so you can update or manually ad the plugin via SSH?
