### ISSUE TITLE
Cant find Audo Service in Repo

### ISSUE THREAD

**Issue by aschnabl** [lsellens/script.service.audo#16]
Hi

I've reinstalled Audo to fix a problem but it keeps telling me to install the audo service, but i can not longer find it listed in your repo??

**Comment by jo3rg** [comment]
I also had to manually install it from:
http://lsellens.openelec.tv/addons/repo/script.service.audo/
Is it possible that the service "audo" isn't included in the repo any more?
BR J

**Comment by lsellens** [comment]
That is the repo. Sometimes you have to force refresh repositories in kodi if some things are not showing up.
