### ISSUE TITLE
Update Detected. Stopping Service

### ISSUE THREAD

**Issue by hypnot0ad** [lsellens/script.service.audo#17]
These Kodi notifications started occurring a couple of days ago (I think an auto update was pushed). As far as I can tell the only thing that may have changed recently is that audo-dependencies now includes transmission?

The notification received is:
audo. update detected: Stopping Services now

and:
audo. update detected: Restarting Services now

Any ideas?

Let me know what logs etc. I need to upload.

**Comment by lsellens** [comment]
Should be fixed in this version http://lsellens.openelec.tv/addons/devrepo/script.service.audo/script.service.audo-1.2.2~beta12.zip
