### ISSUE TITLE
Couchpotato not starting if there is an existing couchpotatoserver.ini file

### ISSUE THREAD

**Issue by TH3-M0L3** [lsellens/script.service.audo#21]
This has been happening for a while. I tried sorting it a number of ties, but whenever I post about it i get no responses.

to recreate
1. KODI & CP, SAB SR & HP running normally
2. Restart KODI
3. KODI, SAB, SR & HP all start, except CP
4. Rename couchpotatoserver.ini to couchpotatoserver.ini.bak
5. Restart KODI
6. KODI & CP, SAB SR & HP running normally
7. Rename couchpotatoserver.ini.bak to couchpotatoserver.ini
8. From CP GUI: restart CP in order to load the correct ini file

all log files are [https://www.dropbox.com/s/0k9kne93eogcei2/log-2016-09-10-13.09.54.zip?dl=0](url)

**Comment by lsellens** [comment]
Is this still an issue?

**Comment by TH3-M0L3** [comment]
Hi Isellens

Yes, it sure is. 

Let me know if you want updated logs etc.

**Comment by lsellens** [comment]
Something is getting into your cp.ini that configobj can't parse. Is it only crashing after you go into the settings and set everything up? Can you send me one of the ini files that causes it to crash? Email it to me my github name at gmail.com

**Comment by TH3-M0L3** [comment]
Hi Isellens

Have emailed you as requested

**Comment by TH3-M0L3** [comment]
I can't quite remember how it started to crash, and it was just trial & error when I discovered that removing the ini file resulted in cp GUI starting normally when KODI reboots. 

Similarly, deleting the newly created ini file and replacing it with the original ini before restarting just cp from its own GUI means I don't have to constantly set it all up again.

**Comment by TH3-M0L3** [comment]
I had not long before had a corrupted CP database folder, which resolved itself when I renamed the original database folder and restarted CP. 

I was using that same line of thought to resolve this issue.

**Comment by lsellens** [comment]
In a list value you can not mix quoted with unquoted attributes. See here
http://www.voidspace.org.uk/python/configobj.html#list-values
line 525 in your couchpotatoserver.ini is
required_words = "BluRay&H264&AAC&RARBG", obfuscated
please change to
required_words = "BluRay&H264&AAC&RARBG", "obfuscated"
Closing this for now. Will see about patching couchpotato source to prevent this scenario.

**Comment by TH3-M0L3** [comment]
Thanks for the help! 

Sorted.
