### ISSUE TITLE
nzbToMedia - ImportError: No module named six.moves

### ISSUE THREAD

**Issue by tcamargo** [lsellens/script.service.audo#22]
Hi,

Since last update (1.26), nzbToMedia does not work anymore. It seems we are missing a lot of dependencies for nzbToMedia-V11.01. At least, six, requestes, rebulk, babelfish, and setuptools python modules need to be installed. I tried to add all manually but had trouble with setuptools.

Running LibreELEC (community) - Version: 7.90.008.

Thanks!
Tiago

**Comment by lsellens** [comment]
Thanks for letting me know. I don't use nzbtomedia and there was nothing in changelogs about needing extra dependencies. I'll get it fixed soon.

**Comment by lsellens** [comment]
Could you post me the log with the exact error?

**Comment by lsellens** [comment]
Looking through the code changes since the previous version I'm not seeing any dependency changes. Six for instance should already be installed on your system as per line 9 in https://github.com/lsellens/script.service.audo/blob/master/script.service.audo/addon.xml Maybe reboot and see if problem still exists? I know it's silly but might just be a namespace path issue. Either way send me some logs. Thanks!

**Comment by tcamargo** [comment]
Traceback (most recent call last):
  File "/storage/.kodi/userdata/addon_data/script.service.audo/scripts/nzbToSickBeard.py", line 251, in <module>
    import nzbToMedia
  File "/storage/.kodi/addons/script.service.audo/resources/nzbToMedia/nzbToMedia.py", line 514, in <module>
    import core
  File "/storage/.kodi/addons/script.service.audo/resources/nzbToMedia/core/__init__.py", line 33, in <module>
    from six.moves import reload_module
ImportError: No module named six.moves

**Comment by tcamargo** [comment]
Just rebooted. Same problem.
BTW, what do you use for post-processing?

Thanks!

**Comment by Jbekker** [comment]
I'm getting the same error, hopefully we find a fix for this soon!

**Comment by TySkby** [comment]
Same issue here following the last upgrade.

**Comment by lsellens** [comment]
I'm going to just roll back versions real quick until I have some time to look into it.

**Comment by lsellens** [comment]
Rolled back to older working version. Please update me on if it works ok or not.

**Comment by tcamargo** [comment]
seems fine.

```
 # python /storage/.kodi/userdata/addon_data/script.service.audo/scripts/nzbToSickBeard.py

[19:11:45] [INFO]::MAIN: Loading config from [/storage/.kodi/userdata/addon_data/script.service.audo/scripts/autoProcessMedia.cfg]
[19:11:45] [INFO]::MAIN: Checking database structure...
[19:11:45] [INFO]::MAIN: Checking if source needs an update
```

Thanks!

**Comment by lsellens** [comment]
Thanks for your testing. I'll find some time to bump it back to the newer version with fixes soon hopefully.
