### ISSUE TITLE
Nzbtomedia scripts

### ISSUE THREAD

**Issue by Morphy99** [lsellens/script.service.audo#24]
Not sure why you rolled back 10.15 but I'm having [this](https://github.com/SickRage/SickRage/issues/2865) issue with some sickrage downloads. It's supposed to be fixed in 11.03. Any chance you can update the openelec add-on please?

**Comment by lsellens** [comment]
Sure if you'll test it. I cant remember the reason I had to roll back. I don't use the nzbtomedia scripts so they never really get tested.
http://lsellens.openelec.tv/addons/devrepo/script.service.audo/script.service.audo-1.2.9~beta1.zip

**Comment by Morphy99** [comment]
No problem I'll have a look

**Comment by Morphy99** [comment]
Ok so the scripts don't have the correct perms. Had to chmod +X them. I did post about this in the openelec forum in sabnzbd suite subforum. Obviously you didnt see that :) 
Apart from that, it appears to work correctly for me so far, will continue to test over the next days if you like though.

**Comment by lsellens** [comment]
Yeah I wasn't aware. Can you check if this fixes the permission issues?
http://lsellens.openelec.tv/addons/devrepo/script.service.audo/script.service.audo-1.2.9~beta2.zip
I'd test myself, but I'm sitting in an airport doing this from my phone through ssh right now. Good chance There could be typos.

**Comment by lsellens** [comment]
I had time to test. Looks ok to me. Sent an update to the live repo. Thanks for the help!

**Comment by Morphy99** [comment]
Great, good work from the airport! :D No problem.I'll post here in future if I come across any other issues.
