### ISSUE TITLE
SickRage won't start

### ISSUE THREAD

**Issue by decentaur** [lsellens/script.service.audo#26]
After update 1.2.9 I had to reinstall audo to make all the services start. After the update to 1.3.0 I had to do it again, and that fixed Sab and CouchPotato. But SickRage won't start.
What I could get from the logs:
[journal-cur.txt](https://github.com/lsellens/script.service.audo/files/825793/journal-cur.txt)

Any help would be appreciated.

**Comment by lsellens** [comment]
Could you post your actual kodi debug log please

**Comment by decentaur** [comment]
Do you mean this one:
[log-2017-03-07-21.16.04.zip](https://github.com/lsellens/script.service.audo/files/825847/log-2017-03-07-21.16.04.zip)

**Comment by lsellens** [comment]
turn debugging on then reboot wait a bit and send me that log
http://kodi.wiki/view/Log_file/Advanced

**Comment by decentaur** [comment]
Log file with debugging on:
[log-2017-03-08-07.31.28.zip](https://github.com/lsellens/script.service.audo/files/826927/log-2017-03-08-07.31.28.zip)

**Comment by ChuckyNorris** [comment]
Hi Isellens
I'm having this same problem, only started today though.  (RPi)
I tried manually starting sickbeard.py but got an error saying port 8081 is already in use, even though SB is supposed to be on port 8082.  So I went into config.ini and changed the webserver to 8082, I could then start it manually, but it was like a clean install - no shows, no settings...
Could you maybe reverse the last update?  I'm a noob here so I don't even know how to get a debug log.

Thanks

**Comment by pcortez** [comment]
Hi Isellens 

I think I have the same problem and I could help with some logs. After the update sickbeard didn't start and I tried to do it manually with

`python /storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/SickBeard.py --pidfile
=/var/run/sickbeard.pid --datadir /storage/.kodi/userdata/addon_data/script.service.audo --config=/storage/.kodi/userdata/addon_data/script.service.audo/sickb
eard.ini --daemon`

Then this log showed up
```
Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/SickBeard.py", line 492, in <module>
    SickRage().start()
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/SickBeard.py", line 240, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/__init__.py", line 1078, in initialize
    TORRENT_PASSWORD = check_setting_str(CFG, 'TORRENT', 'torrent_password', censor_log=True)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/config.py", line 643, in check_setting_str
    my_val = helpers.decrypt(config[cfg_name][item_name], encryption_version)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/helpers.py", line 1006, in decrypt
    return encrypt(data, encryption_version, _decrypt=True)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/helpers.py", line 996, in encrypt
    return ''.join(chr(ord(x) ^ ord(y)) for (x, y) in izip(base64.decodestring(data), cycle(sickbeard.ENCRYPTION_SECRET)))
  File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi2.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/base64.py", line 321, in decodestring
binascii.Error: Incorrect padding
```

I hope this will help

Thanks

**Comment by lsellens** [comment]
This should be fixed in script.module.audo-programs-0.4.0
please update, reboot and test.

**Comment by lsellens** [comment]
Actually this might not be resolved. Could one of you guys email me when you get a chance? its my user name at gmail. Thanks

**Comment by decentaur** [comment]
Send you an email, happy to test it, but I'm not seeing the update anywhere.

**Comment by pcortez** [comment]
Same here, I'm not seeing any change in the github network

**Comment by lsellens** [comment]
Update was with a module. I didn't receive an email from any of you.

**Comment by decentaur** [comment]
I've mailed you again did you get it this time? If not you can mail me using lsellens @ foaly.nl
I'm not really sure what I should update.

**Comment by lsellens** [comment]
Can you send me a copy of your sickbeard.ini there is a unparsable object
in there. I'm having trouble duplicating the error on my end. Thanks

**Comment by decentaur** [comment]
Here you go

2017-03-19 17:29 GMT+01:00 lsellens <notifications@github.com>:

> Can you send me a copy of your sickbeard.ini there is a unparsable object
> in there. I'm having trouble duplicating the error on my end. Thanks
>

**Comment by lsellens** [comment]
Under general setting tab go to advanced settings and uncheck encrypt passwords. This will fix it.
