### ISSUE TITLE
Unicode error on sabnzbd 2.0

### ISSUE THREAD

**Issue by Morphy99** [lsellens/script.service.audo#27]
Just noticed this error and the mobile interface isn't loading either, will look into it more when i can but just a heads up:
SABnzbd was started with encoding ANSI_X3.4-1968, this should be UTF-8. Expect problems with Unicoded file and directory names in downloads

**Comment by lsellens** [comment]
There is no default locale set in libreelec/openelec This warning will show up in your logs every time but shouldn't cause the webui not to be up. Probably unrelated. You'll need to turn debugging on in kodi. either post them on pastebin or email them to me when you get a chance. Its my user name at gmail.
https://wiki.libreelec.tv/index.php?title=HOW_TO:Provide_Logfile#tab=Via_Samba_2FSMB

**Comment by lsellens** [comment]
I did find a bug in the version I pushed out last night. Please update to beta2 and if the problem still persists after a reboot then send those logs.

**Comment by Morphy99** [comment]
Just tried beta2 and still that error on startup. Not sure it's caused any issues yet but haven't done much testing. Sorry the web gui is up however the secondary one is no longer a thing in sab 2.0 by the looks of it. I used x.x.x.x/m for my phone and just the regular url on anything else and I could have two different skins. Not sure why they got rid of that. I'll send over kodi logs via email.

**Comment by lsellens** [comment]
The secondary skin option was removed
https://github.com/sabnzbd/sabnzbd/issues/842
I might write a patch to suppress the utf-8 warning but in the mean time it shouldn't effect anything. As per our email let me know if the multicore par warning goes away after a par job is ran or not. Looking at their source I believe it should. Thanks for the testing!

**Comment by lsellens** [comment]
Actually it looks like there is an issue with the version of par2 I compiled. I'll push an update soon.
