### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by Morphy99** [lsellens/script.service.audo#28]
Getting a few errors in the log after the latest update:
 ERROR: AUDO: CouchPotatoServer exception occurred
10:31:08  63.056877 T:1778361248   ERROR: Invalid line at line "536".
10:31:08  63.074619 T:1778361248   ERROR: AUDO: Headphones exception occurred
10:31:08  63.074760 T:1778361248   ERROR: Invalid line at line "185".
10:31:08  63.150799 T:1778361248   ERROR: AUDO: CouchPotato exception occurred
10:31:08  63.150944 T:1778361248   ERROR: Invalid line at line "536".

Everything seems to be working ok so far though. The Locale thing is still happening on Sab too.

**Comment by lsellens** [comment]
Need to reboot after update for locale error to go away. Could you turn debugging on and post a full debug log if error still exists after reboot?
https://wiki.libreelec.tv/index.php?title=HOW_TO:Provide_Logfile#tab=Via_Samba_2FSMB

**Comment by Morphy99** [comment]
I'm now getting an exception with the locale addon:
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 2] No such file or directory
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.locale/default.py", line 74, in <module>
                                                Monitor().waitForAbort()
                                              File "/storage/.kodi/addons/service.locale/default.py", line 30, in __init__
                                                self.setLocale()
                                              File "/storage/.kodi/addons/service.locale/default.py", line 56, in setLocale
                                                subprocess.call(['localedef', '-f', charmap, '-i', locale, localepath])
                                              File "/usr/lib/python2.7/subprocess.py", line 168, in call
                                              File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
                                            OSError: [Errno 2] No such file or directory
                                            -->End of Python script error report<--`

Full debug here:
https://pastebin.com/n8v0uzme

**Comment by lsellens** [comment]
I haven't tested it on openelec. It will probably be a while before I have time to look into this. Its tested and working on libreelec. I would suggest switching since LE also has active development and way better support.

**Comment by Morphy99** [comment]
Yea been looking to do that but my OE install is quite customised and as far as I'm aware its not a case of just copying over addons from OE to LE.
