### ISSUE TITLE
Installation broke 1.3.2, can't install 1.3.3

### ISSUE THREAD

**Issue by SPRSheep** [lsellens/script.service.audo#29]
Hello Isellens,

First of all, Thank you for your hard work!

When Libreelec auto-installed  Audo, the installation failed. Can you please fix the problem? Thank you in advance!! Here is the log:

https://pastebin.com/PrDZRvwx

**Comment by jvdbrink20** [comment]
I'm getting a 'incompatible' in the add-on information as well. I'm running LibreElec 7.0.3.
Can I do anything to help @lsellens ?

**Comment by jvdbrink20** [comment]
I tried upgrading to LibreElec 8 but no success. The error pointed me in this direction tho:
<import addon="script.module.audo-programs" version="0.4.7"/> is in script.service.audo addon.xml. But the audo-programs version in the repo's xml is only @ 0.4.6

**Comment by lsellens** [comment]
Sorry, typo. Uploading corrected files now. Thanks!
