### ISSUE TITLE
SSL Sabnzbd

### ISSUE THREAD

**Issue by pinhao** [lsellens/script.service.audo#3]
I'm using audo with Openelec 4.95.4 
The option to enable SSL connection to servers is greyed out, I think it's related to Openelec's migration to libressl

Any idea on how to fix it?

**Comment by soverbosch** [comment]
I've got this SSL problem too, using openelec 5.0.0. In the kodi.log I see the following:

23:55:30 T:140032727815936 WARNING: CPythonInvoker(9): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
23:55:30 T:140032727815936   ERROR: AUDO: Error Copying libcrypto for x86_64                               
23:55:30 T:140032727815936   ERROR: [Errno 17] File exists                                                                                                                                
23:55:30 T:140032727815936   ERROR: AUDO: Error Copying libssl for x86_64                               
23:55:30 T:140032727815936   ERROR: [Errno 17] File exists

Don't know how to solve this :'(

**Comment by Vodka2014** [comment]
I have the same issue with [Stable] OpenELEC 5.0.3 (arm) RPi 2.

I have done everything that is mentioned on all forums and still no SSL.  Please let me know if there is a temp fix some where.

Thanks

**Comment by aschnabl** [comment]
I've just done a fresh install on an RPi2 the same as Vodka2014, and also getting the issue.

Is there a specific order the packages should have been applied in?

**Comment by lsellens** [comment]
My RPi2 should be here today or tomorrow. I'll get this fixed.

**Comment by lsellens** [comment]
RPi2 came in today. I have SSL working and will have an update pushed out as soon as I finish a little more testing

**Comment by Vodka2014** [comment]
SSL i still broken for me and i did a clean install.

**Comment by Vodka2014** [comment]
Solved with v1.1.8. Thanks

**Comment by TySkby** [comment]
I'm having this problem as well- tried everything here and keep coming up short.  The kodi.log file has entries like `Error Copying <dependency> for i686`.  

Whenever I delete my `arch.i686` file in /.kodi/addons/script.module.audo-dependencies, it keeps coming back.  Anything I can do to get this working?

Running OpenELEC 5.0.8 Generic 32-bit build.

Thanks!

**Comment by lsellens** [comment]
I'm no longer including 32bit binaries. Openelec has dropped support for 32bit systems. Install a 64 bit version of openelec.
