### ISSUE TITLE
enable nzb search providers error

### ISSUE THREAD

**Issue by orizzle** [lsellens/script.service.audo#8]
greetings! i am trying to enable nzb search in sickrage (audo) and when i check the "enable nzb search providers" box and click save, my changes aren't actually saved, and i get "AttributeError: 'Config' object has no attribute 'saveSearch'" in my sickrage.log....brand new install of openelec, any ideas?

**Comment by lsellens** [comment]
Tried reproducing this on my setup but was unable to. I posted something for you to try in the OE forum.

**Comment by orizzle** [comment]
I wound up getting the latest commit of sickrage from githib and installed it over top of sickrage from audo. It works great now. Guessing there is some file missing in your repo.
